apiVersion: batch/v1
kind: Job
metadata:
  generateName: trigger-karate-tests-
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: trigger-karate-gha
          image: curlimages/curl
          env:
          - name: GHA_TOKEN
            valueFrom:
              secretKeyRef:
                name: gha-token
                key: token
          - name: TRIGGER_REASON
            value: "argo-examples"
          command:
            - "env"
          command:
            - "curl"
            - "-X"
            - "POST"
            - 'https://api.github.com/repos/clinicalresearchio/crio-testing-automation/actions/workflows/karate-tests.yml/dispatches'
            - "--header"
            - 'Accept: application/vnd.github+json'
            - "--header"
            - "Authorization: token $(GHA_TOKEN)"
            - "--header"
            - 'Content-Type: application/json'
            - "--data-raw"
            - "{\"ref\": \"karate_main\", \"inputs\": {\"trigger_reason\": \"$(TRIGGER_REASON)\", \"trigger_hostname\": \"$(HOSTNAME)\"}}"
      restartPolicy: Never
  backoffLimit: 2
