apiVersion: batch/v1
kind: Job
metadata:
  generateName: trigger-karate-tests-
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: trigger-karate-gha
          image: curlimages/curl
          env:
          - name: GHA_TOKEN
            valueFrom:
              secretKeyRef:
                name: gha-token
                key: token
          command:
            - "curl"
            - "-X"
            - "POST"
            - "'https://api.github.com/repos/nathanchilton/argo-examples/actions/workflows/test.yml/dispatches'"
            - "--header"
            - "'Accept: application/vnd.github+json'"
            - "--header"
            - '--header "Authorization: token $GHA_TOKEN"'
            - "--header"
            - "'Content-Type: application/json'"
            - "--data-raw '{\"ref\": \"master\", \"inputs\": {\"argo_id\": \"1234\"}}'"
      restartPolicy: Never
  backoffLimit: 2
